@data BaseModelicaASTNode begin
    BaseModelicaType(name, fields)
    BaseModelicaPackage(name, class_defs, model)
    BaseModelicaModel(long_class_specifier)
    BaseModelicaConstant(type, name, value, description, modification)
    BaseModelicaParameter(type, name, value, description, modification)
    BaseModelicaVariable(type, name, input_or_output, description, modification)
    BaseModelicaSimpleEquation(lhs, rhs)
    BaseModelicaInitialEquation(equation) # Just holds a BaseModelicaAnyEquation and denotes that it's an initial equation
    BaseModelicaArray(type, length)
    BaseModelicaString(string)
    BaseModelicaTypeSpecifier(type)
    BaseModelicaTypePrefix(final_flag, dpc, io)
    BaseModelicaDeclaration(ident, array_subs, modification)
    BaseModelicaComponentDeclaration(declaration, comment)
    BaseModelicaComponentClause(type_prefix, type_specifier, component_list)
    BaseModelicaComponentReference(ref_list)
    BaseModelicaParameterEquation(component_reference, expression, comment)
    BaseModelicaWhenEquation(whens, thens)
    BaseModelicaForEquation(index, equations)
    BaseModelicaIfEquation(ifs, thens)
    BaseModelicaAnyEquation(equation, description)
    BaseModelicaAnnotation(annotation_content)
    BaseModelicaForIndex(ident, expression)
    BaseModelicaComposition(components, equations, initial_equations)
    BaseModelicaLongClass(name, description, composition)
    BaseModelicaModification(expr)
    #Class types
    BaseModelicaClassDefinition(class_type, class)
end

@data BaseModelicaExpr<:BaseModelicaASTNode begin
    # these are basically just tokens...
    BMAdd()
    BMElementWiseAdd()
    BMSubtract()
    BMElementWiseSubtract()
    BMMult()
    BMElementWiseMult()
    BMDivide()
    BMElementWiseDivide()
    BMColon()
    BMIf()
    BMFor()
    BMWhen()
    BMThen()
    BMLoop()
    BMequation()

    # relational tokens
    BMLessThan()
    BMGreaterThan()
    BMLEQ()
    BMGEQ()
    BMEQ()
    BMNEQ()

    BMAND()
    BMOR()
    BMNOT()

    # nodes in the AST 
    BaseModelicaNumber(val)
    BaseModelicaBool(val)
    BaseModelicaIdentifier(name)
    BaseModelicaSum(left, right)
    BaseModelicaMinus(left, right)
    BaseModelicaUnaryMinus(operand)
    BaseModelicaProd(left, right)
    BaseModelicaFactor(base, exp)
    BaseModelicaElementWiseFactor(base, exp)
    BaseModelicaElementWiseProd(left, right)
    BaseModelicaElementWiseSum(left, right)
    BaseModelicaElementWiseMinus(top, bottom)
    BaseModelicaDivide(top, bottom)
    BaseModelicaElementWiseDivide(left, right)
    BaseModelicaParens(BaseModelicaExpr)
    BaseModelicaFunctionArgs(args)
    BaseModelicaFunctionCall(func_name, args)
    BaseModelicaRange(start, step, stop)
    BaseModelicaArraySubscripts(subscripts)

    # relational nodes
    BaseModelicaNot(relation)
    BaseModelicaAnd(left, right)
    BaseModelicaOr(left, right)
    BaseModelicaLessThan(left, right)
    BaseModelicaGreaterThan(left, right)
    BaseModelicaLEQ(left, right)
    BaseModelicaGEQ(left, right)
    BaseModelicaEQ(left, right)
    BaseModelicaNEQ(left, right)
    BaseModelicaIfExpression(conditions, expressions)
    BaseModelicaArrayReference(term, indexes)
end